# Generated by Django 2.1.5 on 2019-01-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HomePageImage/')),
            ],
            options={
                'verbose_name_plural': 'Home Page Images',
            },
        ),
        migrations.CreateModel(
            name='RateByCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('rate', models.PositiveIntegerField(help_text='rate of product per kg')),
            ],
            options={
                'verbose_name_plural': 'Rate By City',
            },
        ),
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vasudhaBooking.City')),
            ],
            options={
                'verbose_name_plural': 'Rate List',
            },
        ),
        migrations.AddField(
            model_name='ratebycity',
            name='ratelist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vasudhaBooking.RateList'),
        ),
    ]
