# Generated by Django 2.1.5 on 2019-01-31 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vasudhaBooking', '0002_auto_20190131_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('rate', models.PositiveIntegerField(help_text='rate of product per kg')),
            ],
            options={
                'verbose_name_plural': 'Rate Of Product',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.RemoveField(
            model_name='ratelist',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='ratelist',
            name='rate',
        ),
        migrations.AddField(
            model_name='rateofproduct',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vasudhaBooking.RateList'),
        ),
    ]
