# Generated by Django 2.1.5 on 2019-02-10 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vasudhaBooking', '0003_auto_20190131_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Product List',
            },
        ),
        migrations.CreateModel(
            name='SellDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vasudhaBooking.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sell Demands',
            },
        ),
        migrations.AlterField(
            model_name='rateofproduct',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='productlist',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vasudhaBooking.SellDemand'),
        ),
    ]
