# Generated by Django 2.1.5 on 2019-02-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vasudhaBooking', '0005_auto_20190210_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttotalprice',
            name='sell',
        ),
        migrations.AddField(
            model_name='selldemand',
            name='totel_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlistdetail',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vasudhaBooking.SellDemand'),
        ),
        migrations.DeleteModel(
            name='ProductTotalPrice',
        ),
    ]
