# Generated by Django 2.1.5 on 2019-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasudhaBooking', '0006_auto_20190210_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldemand',
            name='total_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
